# Generated by Django 3.1.5 on 2021-01-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_created=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('initial_price', models.IntegerField()),
                ('add_room_price', models.IntegerField()),
                ('add_bathroom_price', models.IntegerField()),
            ],
        ),
    ]
