# Generated by Django 3.1.5 on 2021-01-12 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='add_bathroom_price',
            field=models.IntegerField(verbose_name='Цена дополнительного санузла'),
        ),
        migrations.AlterField(
            model_name='service',
            name='add_room_price',
            field=models.IntegerField(verbose_name='Цена дополнительной комнаты'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('supporting', 'Поддерживающая уборка'), ('full', 'Генеральная уборка'), ('after_renovation', 'Уборка после ремонта')], default='supporting', max_length=60, verbose_name='тип услуги')),
                ('room_count', models.IntegerField(default=1, verbose_name='кол-во комнат')),
                ('bathroom_count', models.IntegerField(default=1, verbose_name='кол-во санузлов')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('order_date', models.DateField(verbose_name='Дата заказа')),
                ('date_created', models.DateField(auto_now=True, verbose_name='Дата создания заказа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
        ),
    ]
