# Generated by Django 3.1.5 on 2021-01-13 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0002_auto_20210112_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service', verbose_name='Тип уборки'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now=True, verbose_name='дата создания отзыва')),
                ('text', models.TextField()),
                ('scores', models.IntegerField(choices=[(1, '1 звезда'), (2, '2 звезды'), (3, '3 звезды'), (4, '3 звезды'), (5, '5 звезд')], verbose_name='оценка')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.order', verbose_name='Заказ, на который оставлают отзыв')),
            ],
        ),
    ]
